name: tudkabir
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.3
  gap: ^3.0.1
  go_router: ^17.0.1
  hooks_riverpod: ^3.1.0
  intl: ^0.20.2
  lottie: ^3.3.2
  supabase_flutter: ^2.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/lottie/
